# Generated by Django 5.2.7 on 2025-10-29 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scooters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('scooter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scooters.scooter')),
            ],
            options={
                'verbose_name': 'Rental',
                'verbose_name_plural': 'Rentals',
            },
        ),
    ]
