# Generated by Django 5.2.7 on 2025-11-02 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scooters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Время аренды')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Время возврата')),
                ('scooter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scooters.scooter', verbose_name='Самокат')),
            ],
            options={
                'verbose_name': 'Арендатор',
                'verbose_name_plural': 'Арендаторы',
            },
        ),
    ]
