# Generated by Django 5.2.7 on 2025-10-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
