# Generated by Django 5.2.7 on 2025-10-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_alter_rental_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
