# Generated by Django 5.2.7 on 2025-10-29 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_alter_rental_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='is_completed',
        ),
    ]
