# Generated by Django 5.2.7 on 2025-10-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('battery_level', models.IntegerField()),
                ('is_available', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Scooter',
                'verbose_name_plural': 'Scooters',
            },
        ),
    ]
