# Generated by Django 5.2.7 on 2025-10-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scooters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scooter',
            name='battery_level',
            field=models.IntegerField(max_length=100),
        ),
    ]
