# Generated by Django 5.2.7 on 2025-11-01 12:24

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scooters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scooter',
            name='slug',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=100, unique=True),
        ),
    ]
