# Generated by Django 5.2.7 on 2025-10-29 18:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scooters', '0002_alter_scooter_battery_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scooter',
            name='battery_level',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
